python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-S028.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-S02.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-S09.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-S11.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-S23.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C001.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C003.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C006.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C010.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C021.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C022.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C037.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C038.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-C041.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Caldor-D014.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-C01.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-C08.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-C10.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-C12.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Dixie-C22.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Creek-043A.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Creek-C034.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Creek-C062.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Creek-C15.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Creek-N01.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/Creek-N02.yml
python /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/early-regen/metashape-configs/derived/120m-01/RMR.yml
